### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by HaithemSouala** [burke-software/django-admin-export#1]
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin_export/export_to_xls/?ct=7&ids=1
Django Version:	1.5.5
Exception Type:	AttributeError
Exception Value:	
<b>'Options' object has no attribute 'model_name'</b>
Exception Location:	C:\Users\user\AppData\Roaming\Python\Python27\site-packages\report_utils\mixins.py in report_to_list, line 189
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.6
Python Path:	
['C:\\Users\\user\\PycharmProjects\\TestModelApp',
 'C:\\Python27\\lib\\site-packages\\setuptools-1.1.5-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\pip-1.4.1-py2.7.egg',
 'C:\\Windows\\system32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python27\\site-packages',
 'C:\\Python27\\lib\\site-packages',
 'C:\\Python27\\lib\\site-packages\\PIL']
Server time:	sam, 12 Avr 2014 22:38:50 +0100

**Comment by bufke** [comment]
Closing due to age.
