### ISSUE TITLE
Where do I select the fields?

### ISSUE THREAD

**Issue by teshomem** [burke-software/django-admin-export#5]
Hi,

This looks very interesting but it is not working for me.

"Go to any admin page, select fields, then select the export to xls action. Then check off any fields you want to export."

Where do I do this? It would be nice if you can include screenshot examples.

T.

**Comment by bufke** [comment]
Go to any admin page. If you had a model Foo it might look like. Actions are [these](https://docs.djangoproject.com/en/1.7/ref/contrib/admin/actions/) 

/admin/foo

**Comment by bufke** [comment]
It's clear to me as is but I'd accept a pull request for better docs
